<a href="https://colab.research.google.com/github/Akash14-09/Machine_Learning/blob/main/Keras_Hyperparameter_Tuning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('/content/diabetes.csv')

In [3]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [4]:
df.corr()['Outcome']

Pregnancies                 0.221898
Glucose                     0.466581
BloodPressure               0.065068
SkinThickness               0.074752
Insulin                     0.130548
BMI                         0.292695
DiabetesPedigreeFunction    0.173844
Age                         0.238356
Outcome                     1.000000
Name: Outcome, dtype: float64

In [5]:
X = df.iloc[: , : -1 ].values
y = df.iloc[: , -1].values

In [7]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X = scaler.fit_transform(X)

In [8]:
X

array([[ 0.63994726,  0.84832379,  0.14964075, ...,  0.20401277,
         0.46849198,  1.4259954 ],
       [-0.84488505, -1.12339636, -0.16054575, ..., -0.68442195,
        -0.36506078, -0.19067191],
       [ 1.23388019,  1.94372388, -0.26394125, ..., -1.10325546,
         0.60439732, -0.10558415],
       ...,
       [ 0.3429808 ,  0.00330087,  0.14964075, ..., -0.73518964,
        -0.68519336, -0.27575966],
       [-0.84488505,  0.1597866 , -0.47073225, ..., -0.24020459,
        -0.37110101,  1.17073215],
       [-0.84488505, -0.8730192 ,  0.04624525, ..., -0.20212881,
        -0.47378505, -0.87137393]])

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
X_train ,y_train , X_test , y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [83]:
import tensorflow as tf
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense ,Dropout

In [12]:
model = Sequential()

In [13]:
model.add(Dense(32,activation='relu',input_dim=8))

model.add(Dense(1,activation='sigmoid'))

model.compile(optimizer='Adam',loss='binary_crossentropy',metrics=['accuracy'])

/usr/local/lib/python3.13/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model.fit(X_train, y_train, batch_size=32, epochs=100, validation_data=(X_test, y_test))

Epoch 1/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.5423 - loss: 0.7084 - val_accuracy: 0.5844 - val_loss: 0.6641
Epoch 2/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6124 - loss: 0.6510 - val_accuracy: 0.6364 - val_loss: 0.6213
Epoch 3/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6710 - loss: 0.6080 - val_accuracy: 0.7078 - val_loss: 0.5867
Epoch 4/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7199 - loss: 0.5727 - val_accuracy: 0.7532 - val_loss: 0.5611
Epoch 5/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7443 - loss: 0.5467 - val_accuracy: 0.7532 - val_loss: 0.5416
Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7557 - loss: 0.5261 - val_accuracy: 0.7468 - val_loss: 0.5274
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7655 - loss: 0.5099 - val_accuracy: 0.7662 - val_loss: 0.5189
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7638 - loss: 0.4981 - val_accuracy: 0.7792 - val_loss: 0.5121
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7671 - loss: 0.4894 - val_accuracy: 0.7727 - val_loss: 0.5068
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7687 - loss: 0.4825 - val_accuracy: 0.7727 - val_loss: 0.5047
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7752 - loss: 0.4762 - val_accuracy: 0.7662 - val_loss: 0.5017
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7752 - loss: 0.4715 - val_accuracy: 0.7597 - val_loss: 0.5025
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7769 - loss: 0.4676 - val_accuracy: 0.7597 - val_loss: 0.5021
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7769 - loss: 0.4645 - val_accuracy: 0.7727 - val_loss: 0.5003
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4615 - val_accuracy: 0.7662 - val_loss: 0.4991
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7769 - loss: 0.4588 - val_accuracy: 0.7662 - val_loss: 0.4988
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7818 - loss: 0.4564 - val_accuracy: 0.7662 - val_loss: 0.5010
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7785 - loss: 0.4540 - val_accuracy: 0.7597 - val_loss: 0.5002
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7834 - loss: 0.4519 - val_accuracy: 0.7597 - val_loss: 0.4999
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7834 - loss: 0.4498 - val_accuracy: 0.7662 - val_loss: 0.5002
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7899 - loss: 0.4481 - val_accuracy: 0.7727 - val_loss: 0.5000
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7932 - loss: 0.4461 - val_accuracy: 0.7727 - val_loss: 0.5005
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7948 - loss: 0.4447 - val_accuracy: 0.7792 - val_loss: 0.5017
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7915 - loss: 0.4430 - val_accuracy: 0.7792 - val_loss: 0.5026
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7932 - loss: 0.4416 - val_accuracy: 0.7792 - val_loss: 0.5052
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7932 - loss: 0.4402 - val_accuracy: 0.7727 - val_loss: 0.5056
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7980 - loss: 0.4390 - val_accuracy: 0.7597 - val_loss: 0.5072
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4378 - val_accuracy: 0.7597 - val_loss: 0.5092
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7980 - loss: 0.4366 - val_accuracy: 0.7662 - val_loss: 0.5087
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4351 - val_accuracy: 0.7662 - val_loss: 0.5090
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4342 - val_accuracy: 0.7597 - val_loss: 0.5104
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7932 - loss: 0.4332 - val_accuracy: 0.7662 - val_loss: 0.5075
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7932 - loss: 0.4323 - val_accuracy: 0.7532 - val_loss: 0.5096
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7932 - loss: 0.4314 - val_accuracy: 0.7468 - val_loss: 0.5119
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7932 - loss: 0.4304 - val_accuracy: 0.7532 - val_loss: 0.5115
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7915 - loss: 0.4296 - val_accuracy: 0.7532 - val_loss: 0.5116
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4288 - val_accuracy: 0.7662 - val_loss: 0.5125
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4277 - val_accuracy: 0.7662 - val_loss: 0.5137
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4267 - val_accuracy: 0.7662 - val_loss: 0.5139
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7932 - loss: 0.4262 - val_accuracy: 0.7597 - val_loss: 0.5158
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4250 - val_accuracy: 0.7662 - val_loss: 0.5160
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4244 - val_accuracy: 0.7597 - val_loss: 0.5154
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7932 - loss: 0.4241 - val_accuracy: 0.7532 - val_loss: 0.5180
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7915 - loss: 0.4233 - val_accuracy: 0.7597 - val_loss: 0.5179
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4226 - val_accuracy: 0.7597 - val_loss: 0.5179
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4213 - val_accuracy: 0.7597 - val_loss: 0.5185
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7964 - loss: 0.4212 - val_accuracy: 0.7597 - val_loss: 0.5177
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7964 - loss: 0.4201 - val_accuracy: 0.7597 - val_loss: 0.5185
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7964 - loss: 0.4193 - val_accuracy: 0.7597 - val_loss: 0.5180
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7964 - loss: 0.4186 - val_accuracy: 0.7597 - val_loss: 0.5200
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7980 - loss: 0.4181 - val_accuracy: 0.7597 - val_loss: 0.5195
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4176 - val_accuracy: 0.7597 - val_loss: 0.5207
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7932 - loss: 0.4174 - val_accuracy: 0.7597 - val_loss: 0.5212
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4165 - val_accuracy: 0.7597 - val_loss: 0.5220
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7932 - loss: 0.4161 - val_accuracy: 0.7597 - val_loss: 0.5224
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7964 - loss: 0.4155 - val_accuracy: 0.7662 - val_loss: 0.5225
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7997 - loss: 0.4148 - val_accuracy: 0.7597 - val_loss: 0.5238
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4144 - val_accuracy: 0.7662 - val_loss: 0.5221
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4140 - val_accuracy: 0.7662 - val_loss: 0.5230
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4130 - val_accuracy: 0.7662 - val_loss: 0.5227
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7980 - loss: 0.4131 - val_accuracy: 0.7662 - val_loss: 0.5221
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4124 - val_accuracy: 0.7662 - val_loss: 0.5220
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7997 - loss: 0.4120 - val_accuracy: 0.7662 - val_loss: 0.5258
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8013 - loss: 0.4114 - val_accuracy: 0.7662 - val_loss: 0.5254
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7997 - loss: 0.4110 - val_accuracy: 0.7727 - val_loss: 0.5247
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8013 - loss: 0.4106 - val_accuracy: 0.7727 - val_loss: 0.5253
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4102 - val_accuracy: 0.7727 - val_loss: 0.5249
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7997 - loss: 0.4096 - val_accuracy: 0.7727 - val_loss: 0.5264
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4089 - val_accuracy: 0.7662 - val_loss: 0.5272
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4089 - val_accuracy: 0.7662 - val_loss: 0.5265
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4083 - val_accuracy: 0.7662 - val_loss: 0.5263
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7980 - loss: 0.4080 - val_accuracy: 0.7727 - val_loss: 0.5267
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7997 - loss: 0.4074 - val_accuracy: 0.7597 - val_loss: 0.5299
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8013 - loss: 0.4075 - val_accuracy: 0.7597 - val_loss: 0.5285
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7980 - loss: 0.4075 - val_accuracy: 0.7662 - val_loss: 0.5277
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8013 - loss: 0.4063 - val_accuracy: 0.7597 - val_loss: 0.5293
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7997 - loss: 0.4059 - val_accuracy: 0.7662 - val_loss: 0.5286
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4053 - val_accuracy: 0.7662 - val_loss: 0.5323
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8046 - loss: 0.4047 - val_accuracy: 0.7532 - val_loss: 0.5323
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8013 - loss: 0.4047 - val_accuracy: 0.7597 - val_loss: 0.5328
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8013 - loss: 0.4050 - val_accuracy: 0.7597 - val_loss: 0.5317
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7997 - loss: 0.4040 - val_accuracy: 0.7662 - val_loss: 0.5288
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8013 - loss: 0.4034 - val_accuracy: 0.7597 - val_loss: 0.5286
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8029 - loss: 0.4033 - val_accuracy: 0.7597 - val_loss: 0.5285
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4028 - val_accuracy: 0.7662 - val_loss: 0.5290
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8046 - loss: 0.4021 - val_accuracy: 0.7532 - val_loss: 0.5298
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8046 - loss: 0.4018 - val_accuracy: 0.7532 - val_loss: 0.5313
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8078 - loss: 0.4016 - val_accuracy: 0.7532 - val_loss: 0.5306
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8062 - loss: 0.4012 - val_accuracy: 0.7532 - val_loss: 0.5308
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8078 - loss: 0.4002 - val_accuracy: 0.7468 - val_loss: 0.5323
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8078 - loss: 0.4004 - val_accuracy: 0.7403 - val_loss: 0.5325
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.3999 - val_accuracy: 0.7532 - val_loss: 0.5317
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.3996 - val_accuracy: 0.7532 - val_loss: 0.5320
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.3996 - val_accuracy: 0.7468 - val_loss: 0.5333
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.3998 - val_accuracy: 0.7532 - val_loss: 0.5345
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8062 - loss: 0.3986 - val_accuracy: 0.7403 - val_loss: 0.5342
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.3985 - val_accuracy: 0.7468 - val_loss: 0.5357
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8046 - loss: 0.3983 - val_accuracy: 0.7468 - val_loss: 0.5357
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8062 - loss: 0.3982 - val_accuracy: 0.7532 - val_loss: 0.5377
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8062 - loss: 0.3975 - val_accuracy: 0.7532 - val_loss: 0.5363

##Things we gonna do

1.How to select appropriate optimizer

2.How to select no of noedes in a layer

3.How to select the no of layers

4.All in all one model

In [17]:
pip install -U keras-tuner

Collecting keras-tuner
  Downloading keras_tuner-1.4.8-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: keras in /usr/local/lib/python3.13/dist-packages (from keras-tuner) (3.13.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.13/dist-packages (from keras-tuner) (26.3)
Requirement already satisfied: requests in /usr/local/lib/python3.13/dist-packages (from keras-tuner) (2.32.4)
Collecting kt-legacy (from keras-tuner)
  Downloading kt_legacy-1.0.5-py3-none-any.whl.metadata (221 bytes)
Requirement already satisfied: grpcio in /usr/local/lib/python3.13/dist-packages (from keras-tuner) (1.84.0)
Requirement already satisfied: protobuf in /usr/local/lib/python3.13/dist-packages (from keras-tuner) (6.33.6)
Requirement already satisfied: typing-extensions~=4.12 in /usr/local/lib/python3.13/dist-packages (from grpcio->keras-tuner) (4.16.0)
Requirement already satisfied: absl-py in /usr/local/lib/python3.13/dist-packages (from keras->keras-tuner) (1.4.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (from keras->keras-tuner) (2.1.3)
Requirement already satisfied: rich in /usr/local/lib/python3.13/dist-packages (from keras->keras-tuner) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.13/dist-packages (from keras->keras-tuner) (0.1.0)
Requirement already satisfied: h5py in /usr/local/lib/python3.13/dist-packages (from keras->keras-tuner) (3.14.0)
Requirement already satisfied: optree in /usr/local/lib/python3.13/dist-packages (from keras->keras-tuner) (0.20.0)
Requirement already satisfied: ml-dtypes in /usr/local/lib/python3.13/dist-packages (from keras->keras-tuner) (0.6.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests->keras-tuner) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests->keras-tuner) (3.20)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests->keras-tuner) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests->keras-tuner) (2026.7.22)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.13/dist-packages (from rich->keras->keras-tuner) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.13/dist-packages (from rich->keras->keras-tuner) (2.21.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.13/dist-packages (from markdown-it-py>=2.2.0->rich->keras->keras-tuner) (0.1.2)
Downloading keras_tuner-1.4.8-py3-none-any.whl (129 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.4/129.4 kB 3.2 MB/s eta 0:00:00
Downloading kt_legacy-1.0.5-py3-none-any.whl (9.6 kB)
Installing collected packages: kt-legacy, keras-tuner
Successfully installed keras-tuner-1.4.8 kt-legacy-1.0.5

In [18]:
import kerastuner as kt

/tmp/ipykernel_1703/1967655440.py:1: DeprecationWarning: `import kerastuner` is deprecated, please use `import keras_tuner`.
  import kerastuner as kt

In [36]:
def build_model(hp):
  model = Sequential()
  model.add(Dense(32,activation='relu',input_dim=8))
  model.add(Dense(1,activation='sigmoid'))


  optimizer = hp.Choice('optimizer' ,values =  ['adam' , 'sgd' , 'rmsprop' , 'adadelta'])

  model.compile(optimizer=optimizer,loss='binary_crossentropy',metrics=['accuracy'])
  return model

In [37]:
tuner = kt.RandomSearch(build_model,
                          objective='val_accuracy',
                          max_trials=5)

Reloading Tuner from ./untitled_project/tuner0.json

In [38]:
tuner.search(X_train , y_train , epochs=5 , validation_data=(X_test , y_test))

In [40]:
tuner.get_best_hyperparameters()[0].values

{'optimizer': 'rmsprop'}

In [41]:
model = tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.13/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.13/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 2 variables whereas the saved optimizer has 6 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [42]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 32)             │           288 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 321 (1.25 KB)

 Trainable params: 321 (1.25 KB)

 Non-trainable params: 0 (0.00 B)

In [43]:
model.fit(X_train, y_train, batch_size=32, epochs=100, validation_data=(X_test, y_test))

Epoch 1/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 3s 56ms/step - accuracy: 0.7671 - loss: 0.5300 - val_accuracy: 0.7468 - val_loss: 0.5557
Epoch 2/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7704 - loss: 0.5130 - val_accuracy: 0.7468 - val_loss: 0.5420
Epoch 3/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7801 - loss: 0.5016 - val_accuracy: 0.7532 - val_loss: 0.5334
Epoch 4/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7801 - loss: 0.4925 - val_accuracy: 0.7597 - val_loss: 0.5275
Epoch 5/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7834 - loss: 0.4846 - val_accuracy: 0.7597 - val_loss: 0.5229
Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7769 - loss: 0.4779 - val_accuracy: 0.7662 - val_loss: 0.5203
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7834 - loss: 0.4720 - val_accuracy: 0.7597 - val_loss: 0.5190
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7883 - loss: 0.4672 - val_accuracy: 0.7532 - val_loss: 0.5158
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7915 - loss: 0.4634 - val_accuracy: 0.7662 - val_loss: 0.5147
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7818 - loss: 0.4592 - val_accuracy: 0.7597 - val_loss: 0.5135
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7866 - loss: 0.4560 - val_accuracy: 0.7532 - val_loss: 0.5125
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7915 - loss: 0.4534 - val_accuracy: 0.7597 - val_loss: 0.5119
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7883 - loss: 0.4502 - val_accuracy: 0.7597 - val_loss: 0.5117
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4483 - val_accuracy: 0.7662 - val_loss: 0.5118
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4459 - val_accuracy: 0.7597 - val_loss: 0.5120
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4442 - val_accuracy: 0.7597 - val_loss: 0.5131
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4429 - val_accuracy: 0.7662 - val_loss: 0.5121
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4413 - val_accuracy: 0.7662 - val_loss: 0.5137
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4399 - val_accuracy: 0.7662 - val_loss: 0.5142
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4390 - val_accuracy: 0.7662 - val_loss: 0.5147
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7915 - loss: 0.4374 - val_accuracy: 0.7662 - val_loss: 0.5160
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7915 - loss: 0.4364 - val_accuracy: 0.7662 - val_loss: 0.5168
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4353 - val_accuracy: 0.7597 - val_loss: 0.5169
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4340 - val_accuracy: 0.7662 - val_loss: 0.5177
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7915 - loss: 0.4332 - val_accuracy: 0.7662 - val_loss: 0.5170
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7932 - loss: 0.4322 - val_accuracy: 0.7597 - val_loss: 0.5180
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4309 - val_accuracy: 0.7662 - val_loss: 0.5197
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7915 - loss: 0.4304 - val_accuracy: 0.7532 - val_loss: 0.5220
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4294 - val_accuracy: 0.7532 - val_loss: 0.5225
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7964 - loss: 0.4289 - val_accuracy: 0.7532 - val_loss: 0.5234
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7964 - loss: 0.4275 - val_accuracy: 0.7532 - val_loss: 0.5239
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7980 - loss: 0.4267 - val_accuracy: 0.7597 - val_loss: 0.5246
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7915 - loss: 0.4265 - val_accuracy: 0.7532 - val_loss: 0.5263
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7915 - loss: 0.4249 - val_accuracy: 0.7597 - val_loss: 0.5265
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4244 - val_accuracy: 0.7597 - val_loss: 0.5255
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4237 - val_accuracy: 0.7597 - val_loss: 0.5278
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7915 - loss: 0.4233 - val_accuracy: 0.7532 - val_loss: 0.5288
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7980 - loss: 0.4228 - val_accuracy: 0.7532 - val_loss: 0.5302
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7932 - loss: 0.4222 - val_accuracy: 0.7532 - val_loss: 0.5296
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4213 - val_accuracy: 0.7532 - val_loss: 0.5289
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7915 - loss: 0.4206 - val_accuracy: 0.7532 - val_loss: 0.5286
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4203 - val_accuracy: 0.7532 - val_loss: 0.5290
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4192 - val_accuracy: 0.7532 - val_loss: 0.5295
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8013 - loss: 0.4192 - val_accuracy: 0.7532 - val_loss: 0.5298
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7932 - loss: 0.4188 - val_accuracy: 0.7532 - val_loss: 0.5284
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7980 - loss: 0.4180 - val_accuracy: 0.7468 - val_loss: 0.5291
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7932 - loss: 0.4176 - val_accuracy: 0.7597 - val_loss: 0.5293
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7964 - loss: 0.4174 - val_accuracy: 0.7468 - val_loss: 0.5297
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7997 - loss: 0.4167 - val_accuracy: 0.7468 - val_loss: 0.5300
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8029 - loss: 0.4162 - val_accuracy: 0.7468 - val_loss: 0.5299
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4157 - val_accuracy: 0.7532 - val_loss: 0.5300
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7980 - loss: 0.4155 - val_accuracy: 0.7532 - val_loss: 0.5301
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7980 - loss: 0.4150 - val_accuracy: 0.7403 - val_loss: 0.5323
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8029 - loss: 0.4142 - val_accuracy: 0.7468 - val_loss: 0.5320
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8013 - loss: 0.4142 - val_accuracy: 0.7532 - val_loss: 0.5315
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7915 - loss: 0.4134 - val_accuracy: 0.7532 - val_loss: 0.5313
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4131 - val_accuracy: 0.7532 - val_loss: 0.5323
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4129 - val_accuracy: 0.7597 - val_loss: 0.5336
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4124 - val_accuracy: 0.7597 - val_loss: 0.5338
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4117 - val_accuracy: 0.7532 - val_loss: 0.5352
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4115 - val_accuracy: 0.7468 - val_loss: 0.5365
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4107 - val_accuracy: 0.7532 - val_loss: 0.5349
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7997 - loss: 0.4105 - val_accuracy: 0.7532 - val_loss: 0.5361
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7980 - loss: 0.4099 - val_accuracy: 0.7468 - val_loss: 0.5380
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8046 - loss: 0.4098 - val_accuracy: 0.7468 - val_loss: 0.5368
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4090 - val_accuracy: 0.7273 - val_loss: 0.5365
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7980 - loss: 0.4087 - val_accuracy: 0.7273 - val_loss: 0.5369
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8029 - loss: 0.4088 - val_accuracy: 0.7338 - val_loss: 0.5378
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8029 - loss: 0.4080 - val_accuracy: 0.7273 - val_loss: 0.5388
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4083 - val_accuracy: 0.7273 - val_loss: 0.5390
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8078 - loss: 0.4075 - val_accuracy: 0.7273 - val_loss: 0.5398
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8078 - loss: 0.4071 - val_accuracy: 0.7338 - val_loss: 0.5403
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8111 - loss: 0.4066 - val_accuracy: 0.7468 - val_loss: 0.5384
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8094 - loss: 0.4066 - val_accuracy: 0.7468 - val_loss: 0.5399
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8062 - loss: 0.4063 - val_accuracy: 0.7532 - val_loss: 0.5400
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7997 - loss: 0.4060 - val_accuracy: 0.7338 - val_loss: 0.5419
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8013 - loss: 0.4056 - val_accuracy: 0.7403 - val_loss: 0.5427
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8062 - loss: 0.4056 - val_accuracy: 0.7338 - val_loss: 0.5429
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8029 - loss: 0.4051 - val_accuracy: 0.7338 - val_loss: 0.5435
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8062 - loss: 0.4046 - val_accuracy: 0.7338 - val_loss: 0.5454
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8127 - loss: 0.4041 - val_accuracy: 0.7338 - val_loss: 0.5446
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8094 - loss: 0.4040 - val_accuracy: 0.7403 - val_loss: 0.5438
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8143 - loss: 0.4034 - val_accuracy: 0.7468 - val_loss: 0.5434
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8111 - loss: 0.4031 - val_accuracy: 0.7403 - val_loss: 0.5428
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8111 - loss: 0.4030 - val_accuracy: 0.7338 - val_loss: 0.5441
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8111 - loss: 0.4031 - val_accuracy: 0.7338 - val_loss: 0.5440
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8160 - loss: 0.4021 - val_accuracy: 0.7273 - val_loss: 0.5452
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8111 - loss: 0.4021 - val_accuracy: 0.7338 - val_loss: 0.5445
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8127 - loss: 0.4020 - val_accuracy: 0.7468 - val_loss: 0.5441
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8127 - loss: 0.4013 - val_accuracy: 0.7532 - val_loss: 0.5428
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8160 - loss: 0.4014 - val_accuracy: 0.7532 - val_loss: 0.5442
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8111 - loss: 0.4006 - val_accuracy: 0.7403 - val_loss: 0.5463
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8160 - loss: 0.4008 - val_accuracy: 0.7403 - val_loss: 0.5453
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8143 - loss: 0.3998 - val_accuracy: 0.7468 - val_loss: 0.5451
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8143 - loss: 0.4000 - val_accuracy: 0.7403 - val_loss: 0.5445
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8143 - loss: 0.3995 - val_accuracy: 0.7532 - val_loss: 0.5447
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8143 - loss: 0.3992 - val_accuracy: 0.7532 - val_loss: 0.5442
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8160 - loss: 0.3996 - val_accuracy: 0.7532 - val_loss: 0.5471
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8208 - loss: 0.3986 - val_accuracy: 0.7468 - val_loss: 0.5487
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8176 - loss: 0.3985 - val_accuracy: 0.7468 - val_loss: 0.5494

In [58]:
def build_model(hp) :
  model = Sequential()
  model.add(Dense(32,activation='relu',input_dim=8))

  units = hp.Int( 'units' , min_value = 8 , max_value = 128 , step = 8)

  model.add(Dense(units=units,activation='relu'))

  model.add(Dense(1,activation='sigmoid'))


  model.compile(optimizer='rmsprop',loss='binary_crossentropy',metrics=['accuracy'])
  return model

In [59]:
tuner = kt.RandomSearch(build_model,
                          objective='val_accuracy',
                          max_trials=5, directory = 'mydir', project_name = 'Anubhav')

Reloading Tuner from mydir/Anubhav/tuner0.json

In [60]:
tuner.search(X_train , y_train , epochs=5 , validation_data=(X_test , y_test))

In [61]:
tuner.get_best_hyperparameters()[0].values

{'units': 32}

In [62]:
model = tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.13/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.13/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 2 variables whereas the saved optimizer has 8 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [63]:
model.fit(X_train, y_train, batch_size=32, epochs=100,initial_epoch=6 ,  validation_data=(X_test, y_test))

Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.7704 - loss: 0.4701 - val_accuracy: 0.7922 - val_loss: 0.4873
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4563 - val_accuracy: 0.7857 - val_loss: 0.4890
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4507 - val_accuracy: 0.7857 - val_loss: 0.4876
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4465 - val_accuracy: 0.7792 - val_loss: 0.4864
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4414 - val_accuracy: 0.7857 - val_loss: 0.4892
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4387 - val_accuracy: 0.7792 - val_loss: 0.4928
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4350 - val_accuracy: 0.7727 - val_loss: 0.4937
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7932 - loss: 0.4322 - val_accuracy: 0.7792 - val_loss: 0.4969
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4288 - val_accuracy: 0.7727 - val_loss: 0.4953
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7948 - loss: 0.4258 - val_accuracy: 0.7662 - val_loss: 0.4969
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7932 - loss: 0.4248 - val_accuracy: 0.7727 - val_loss: 0.5011
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8013 - loss: 0.4215 - val_accuracy: 0.7532 - val_loss: 0.5045
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7980 - loss: 0.4200 - val_accuracy: 0.7662 - val_loss: 0.5076
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7980 - loss: 0.4169 - val_accuracy: 0.7792 - val_loss: 0.5091
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8078 - loss: 0.4152 - val_accuracy: 0.7727 - val_loss: 0.5126
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8111 - loss: 0.4140 - val_accuracy: 0.7662 - val_loss: 0.5104
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8078 - loss: 0.4114 - val_accuracy: 0.7727 - val_loss: 0.5151
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8094 - loss: 0.4104 - val_accuracy: 0.7662 - val_loss: 0.5143
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8094 - loss: 0.4091 - val_accuracy: 0.7597 - val_loss: 0.5125
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4064 - val_accuracy: 0.7597 - val_loss: 0.5155
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8094 - loss: 0.4051 - val_accuracy: 0.7532 - val_loss: 0.5234
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8143 - loss: 0.4035 - val_accuracy: 0.7597 - val_loss: 0.5257
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8192 - loss: 0.4015 - val_accuracy: 0.7532 - val_loss: 0.5294
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8143 - loss: 0.4006 - val_accuracy: 0.7468 - val_loss: 0.5300
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8143 - loss: 0.3986 - val_accuracy: 0.7532 - val_loss: 0.5305
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8143 - loss: 0.3970 - val_accuracy: 0.7662 - val_loss: 0.5315
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8127 - loss: 0.3953 - val_accuracy: 0.7597 - val_loss: 0.5341
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8111 - loss: 0.3939 - val_accuracy: 0.7597 - val_loss: 0.5365
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8160 - loss: 0.3935 - val_accuracy: 0.7597 - val_loss: 0.5366
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8143 - loss: 0.3897 - val_accuracy: 0.7597 - val_loss: 0.5375
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8241 - loss: 0.3889 - val_accuracy: 0.7403 - val_loss: 0.5399
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8208 - loss: 0.3875 - val_accuracy: 0.7403 - val_loss: 0.5380
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8192 - loss: 0.3857 - val_accuracy: 0.7468 - val_loss: 0.5436
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8208 - loss: 0.3861 - val_accuracy: 0.7403 - val_loss: 0.5430
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8192 - loss: 0.3834 - val_accuracy: 0.7532 - val_loss: 0.5484
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8208 - loss: 0.3823 - val_accuracy: 0.7468 - val_loss: 0.5487
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8160 - loss: 0.3808 - val_accuracy: 0.7403 - val_loss: 0.5470
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8257 - loss: 0.3803 - val_accuracy: 0.7403 - val_loss: 0.5475
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8306 - loss: 0.3780 - val_accuracy: 0.7403 - val_loss: 0.5477
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8208 - loss: 0.3773 - val_accuracy: 0.7338 - val_loss: 0.5548
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8241 - loss: 0.3769 - val_accuracy: 0.7338 - val_loss: 0.5531
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8241 - loss: 0.3744 - val_accuracy: 0.7338 - val_loss: 0.5568
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8241 - loss: 0.3738 - val_accuracy: 0.7338 - val_loss: 0.5608
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8306 - loss: 0.3716 - val_accuracy: 0.7338 - val_loss: 0.5603
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8404 - loss: 0.3699 - val_accuracy: 0.7338 - val_loss: 0.5672
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8274 - loss: 0.3705 - val_accuracy: 0.7273 - val_loss: 0.5640
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8241 - loss: 0.3686 - val_accuracy: 0.7273 - val_loss: 0.5576
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8339 - loss: 0.3675 - val_accuracy: 0.7273 - val_loss: 0.5645
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8355 - loss: 0.3657 - val_accuracy: 0.7338 - val_loss: 0.5707
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8306 - loss: 0.3650 - val_accuracy: 0.7273 - val_loss: 0.5665
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8404 - loss: 0.3639 - val_accuracy: 0.7338 - val_loss: 0.5716
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8355 - loss: 0.3630 - val_accuracy: 0.7338 - val_loss: 0.5688
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8290 - loss: 0.3616 - val_accuracy: 0.7338 - val_loss: 0.5699
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8322 - loss: 0.3608 - val_accuracy: 0.7273 - val_loss: 0.5702
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8306 - loss: 0.3593 - val_accuracy: 0.7273 - val_loss: 0.5728
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8355 - loss: 0.3578 - val_accuracy: 0.7338 - val_loss: 0.5793
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8420 - loss: 0.3583 - val_accuracy: 0.7273 - val_loss: 0.5779
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8404 - loss: 0.3567 - val_accuracy: 0.7273 - val_loss: 0.5773
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8322 - loss: 0.3544 - val_accuracy: 0.7273 - val_loss: 0.5784
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8388 - loss: 0.3538 - val_accuracy: 0.7273 - val_loss: 0.5736
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8388 - loss: 0.3534 - val_accuracy: 0.7403 - val_loss: 0.5817
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8436 - loss: 0.3529 - val_accuracy: 0.7273 - val_loss: 0.5832
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8420 - loss: 0.3501 - val_accuracy: 0.7273 - val_loss: 0.5812
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8420 - loss: 0.3498 - val_accuracy: 0.7338 - val_loss: 0.5833
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8420 - loss: 0.3483 - val_accuracy: 0.7273 - val_loss: 0.5830
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8436 - loss: 0.3476 - val_accuracy: 0.7273 - val_loss: 0.5862
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8436 - loss: 0.3456 - val_accuracy: 0.7338 - val_loss: 0.5844
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8485 - loss: 0.3455 - val_accuracy: 0.7273 - val_loss: 0.5890
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8388 - loss: 0.3454 - val_accuracy: 0.7338 - val_loss: 0.5938
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8420 - loss: 0.3433 - val_accuracy: 0.7208 - val_loss: 0.5937
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8550 - loss: 0.3416 - val_accuracy: 0.7208 - val_loss: 0.5950
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8534 - loss: 0.3407 - val_accuracy: 0.7208 - val_loss: 0.5980
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8404 - loss: 0.3410 - val_accuracy: 0.7273 - val_loss: 0.5946
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8550 - loss: 0.3385 - val_accuracy: 0.7273 - val_loss: 0.5949
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8469 - loss: 0.3374 - val_accuracy: 0.7273 - val_loss: 0.5949
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8534 - loss: 0.3369 - val_accuracy: 0.7078 - val_loss: 0.6023
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8420 - loss: 0.3363 - val_accuracy: 0.7338 - val_loss: 0.6004
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8371 - loss: 0.3349 - val_accuracy: 0.7403 - val_loss: 0.5994
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8485 - loss: 0.3335 - val_accuracy: 0.7338 - val_loss: 0.6088
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8469 - loss: 0.3329 - val_accuracy: 0.7468 - val_loss: 0.6107
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8534 - loss: 0.3325 - val_accuracy: 0.7338 - val_loss: 0.6184
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8453 - loss: 0.3324 - val_accuracy: 0.7273 - val_loss: 0.6115
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8502 - loss: 0.3298 - val_accuracy: 0.7273 - val_loss: 0.6156
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8567 - loss: 0.3284 - val_accuracy: 0.7273 - val_loss: 0.6130
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8485 - loss: 0.3261 - val_accuracy: 0.7338 - val_loss: 0.6184
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8550 - loss: 0.3275 - val_accuracy: 0.7273 - val_loss: 0.6162
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8485 - loss: 0.3262 - val_accuracy: 0.7208 - val_loss: 0.6200
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8567 - loss: 0.3260 - val_accuracy: 0.7338 - val_loss: 0.6195
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8518 - loss: 0.3238 - val_accuracy: 0.7338 - val_loss: 0.6202
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8616 - loss: 0.3232 - val_accuracy: 0.7273 - val_loss: 0.6269
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8502 - loss: 0.3218 - val_accuracy: 0.7338 - val_loss: 0.6264
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8567 - loss: 0.3212 - val_accuracy: 0.7273 - val_loss: 0.6240
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8469 - loss: 0.3193 - val_accuracy: 0.7403 - val_loss: 0.6267
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8567 - loss: 0.3182 - val_accuracy: 0.7208 - val_loss: 0.6403

In [64]:
def build_model(hp):
  model = Sequential()
  model.add(Dense(72 , activation= 'relu' , input_dim = 8))

  for i in range(hp.Int('num_layers' , min_value = 1 , max_value = 10)):

    model.add(Dense(72 , activation='relu'))

  model.add(Dense(1 , activation='sigmoid'))


  model.compile(optimizer = 'rmsprop' , loss = 'binary_crossentropy' , metrics = ['accuracy'])

  return model

In [66]:
tuner = kt.RandomSearch(build_model , objective = 'val_accuracy' , max_trials = 3 , directory = 'mydir' , project_name = 'num_layers')

/usr/local/lib/python3.13/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [67]:
tuner.search(X_train , y_train , epochs=5 , validation_data=(X_test , y_test))

Trial 3 Complete [00h 00m 04s]
val_accuracy: 0.7727272510528564

Best val_accuracy So Far: 0.8051947951316833
Total elapsed time: 00h 00m 10s

In [68]:
tuner.get_best_hyperparameters()[0].values

{'num_layers': 3}

In [69]:
model = tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.13/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.13/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 2 variables whereas the saved optimizer has 12 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [71]:
model.fit(X_train, y_train, batch_size=32, epochs=100,initial_epoch=6 ,  validation_data=(X_test, y_test))

Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - accuracy: 0.7997 - loss: 0.4291 - val_accuracy: 0.7208 - val_loss: 0.5438
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8094 - loss: 0.4086 - val_accuracy: 0.7727 - val_loss: 0.5600
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8062 - loss: 0.4009 - val_accuracy: 0.7532 - val_loss: 0.5494
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8176 - loss: 0.3966 - val_accuracy: 0.7338 - val_loss: 0.5387
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8176 - loss: 0.3900 - val_accuracy: 0.7013 - val_loss: 0.5767
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8257 - loss: 0.3831 - val_accuracy: 0.7727 - val_loss: 0.5779
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8241 - loss: 0.3777 - val_accuracy: 0.7597 - val_loss: 0.5594
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8371 - loss: 0.3690 - val_accuracy: 0.7597 - val_loss: 0.5841
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8257 - loss: 0.3638 - val_accuracy: 0.7403 - val_loss: 0.5919
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8404 - loss: 0.3623 - val_accuracy: 0.7078 - val_loss: 0.5907
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8469 - loss: 0.3519 - val_accuracy: 0.7338 - val_loss: 0.6131
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8436 - loss: 0.3483 - val_accuracy: 0.6623 - val_loss: 0.6169
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8420 - loss: 0.3415 - val_accuracy: 0.7403 - val_loss: 0.6174
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8453 - loss: 0.3292 - val_accuracy: 0.6883 - val_loss: 0.6674
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8534 - loss: 0.3289 - val_accuracy: 0.7338 - val_loss: 0.6739
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8518 - loss: 0.3240 - val_accuracy: 0.6948 - val_loss: 0.6408
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8648 - loss: 0.3110 - val_accuracy: 0.6494 - val_loss: 0.7258
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8502 - loss: 0.3205 - val_accuracy: 0.7403 - val_loss: 0.6581
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8697 - loss: 0.2980 - val_accuracy: 0.7468 - val_loss: 0.7314
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8762 - loss: 0.2949 - val_accuracy: 0.7273 - val_loss: 0.7045
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8795 - loss: 0.2895 - val_accuracy: 0.7338 - val_loss: 0.7032
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8827 - loss: 0.2833 - val_accuracy: 0.7403 - val_loss: 0.7421
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8762 - loss: 0.2824 - val_accuracy: 0.7468 - val_loss: 0.6901
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8811 - loss: 0.2636 - val_accuracy: 0.6948 - val_loss: 0.7533
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8941 - loss: 0.2646 - val_accuracy: 0.6623 - val_loss: 0.7577
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8974 - loss: 0.2630 - val_accuracy: 0.7143 - val_loss: 0.7731
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8958 - loss: 0.2429 - val_accuracy: 0.6623 - val_loss: 0.8256
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9039 - loss: 0.2435 - val_accuracy: 0.6948 - val_loss: 0.8156
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9121 - loss: 0.2325 - val_accuracy: 0.6753 - val_loss: 0.9498
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9055 - loss: 0.2408 - val_accuracy: 0.7078 - val_loss: 0.8332
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9153 - loss: 0.2244 - val_accuracy: 0.7078 - val_loss: 0.8562
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9137 - loss: 0.2137 - val_accuracy: 0.6753 - val_loss: 0.9312
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9202 - loss: 0.2054 - val_accuracy: 0.6948 - val_loss: 0.8857
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9251 - loss: 0.2006 - val_accuracy: 0.6818 - val_loss: 0.9419
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9169 - loss: 0.1986 - val_accuracy: 0.6818 - val_loss: 1.0207
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9251 - loss: 0.1929 - val_accuracy: 0.6753 - val_loss: 0.9896
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9365 - loss: 0.1773 - val_accuracy: 0.6753 - val_loss: 1.0376
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9316 - loss: 0.1747 - val_accuracy: 0.6688 - val_loss: 1.0354
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9283 - loss: 0.1768 - val_accuracy: 0.6753 - val_loss: 1.0253
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9397 - loss: 0.1751 - val_accuracy: 0.6494 - val_loss: 1.1073
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9365 - loss: 0.1550 - val_accuracy: 0.6948 - val_loss: 1.2326
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9397 - loss: 0.1838 - val_accuracy: 0.6688 - val_loss: 1.0668
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9577 - loss: 0.1390 - val_accuracy: 0.6558 - val_loss: 1.2049
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9381 - loss: 0.1504 - val_accuracy: 0.6818 - val_loss: 1.1738
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9577 - loss: 0.1208 - val_accuracy: 0.6429 - val_loss: 1.1643
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9397 - loss: 0.1432 - val_accuracy: 0.6753 - val_loss: 1.2405
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9642 - loss: 0.1065 - val_accuracy: 0.6883 - val_loss: 1.1577
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9560 - loss: 0.1307 - val_accuracy: 0.6688 - val_loss: 1.2172
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9511 - loss: 0.1254 - val_accuracy: 0.6688 - val_loss: 1.2612
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9691 - loss: 0.0991 - val_accuracy: 0.6558 - val_loss: 1.3820
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9560 - loss: 0.1084 - val_accuracy: 0.6883 - val_loss: 1.4830
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9674 - loss: 0.0990 - val_accuracy: 0.6818 - val_loss: 1.4540
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9707 - loss: 0.0931 - val_accuracy: 0.6623 - val_loss: 1.5304
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9723 - loss: 0.0832 - val_accuracy: 0.6753 - val_loss: 1.5944
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9707 - loss: 0.0826 - val_accuracy: 0.6818 - val_loss: 1.5606
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9593 - loss: 0.1125 - val_accuracy: 0.6753 - val_loss: 1.5214
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9805 - loss: 0.0717 - val_accuracy: 0.6623 - val_loss: 1.5908
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9772 - loss: 0.0721 - val_accuracy: 0.6818 - val_loss: 1.5826
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9756 - loss: 0.0947 - val_accuracy: 0.6623 - val_loss: 1.6135
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9919 - loss: 0.0471 - val_accuracy: 0.6753 - val_loss: 1.6255
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9805 - loss: 0.0654 - val_accuracy: 0.6494 - val_loss: 1.7176
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9723 - loss: 0.0750 - val_accuracy: 0.6753 - val_loss: 1.6831
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9821 - loss: 0.0536 - val_accuracy: 0.6753 - val_loss: 1.7806
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9788 - loss: 0.0752 - val_accuracy: 0.7078 - val_loss: 1.7004
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9870 - loss: 0.0495 - val_accuracy: 0.6948 - val_loss: 1.8060
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9886 - loss: 0.0490 - val_accuracy: 0.6623 - val_loss: 1.8927
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9870 - loss: 0.0449 - val_accuracy: 0.6623 - val_loss: 1.8668
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9886 - loss: 0.0382 - val_accuracy: 0.6753 - val_loss: 2.0891
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9805 - loss: 0.0564 - val_accuracy: 0.6688 - val_loss: 2.1756
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9805 - loss: 0.0457 - val_accuracy: 0.6494 - val_loss: 2.1475
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9919 - loss: 0.0335 - val_accuracy: 0.6818 - val_loss: 2.0664
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9837 - loss: 0.0490 - val_accuracy: 0.7013 - val_loss: 1.9401
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9919 - loss: 0.0341 - val_accuracy: 0.6753 - val_loss: 2.0106
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9984 - loss: 0.0190 - val_accuracy: 0.6623 - val_loss: 2.2459
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9902 - loss: 0.0387 - val_accuracy: 0.6753 - val_loss: 2.2895
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9919 - loss: 0.0279 - val_accuracy: 0.6688 - val_loss: 2.3938
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9756 - loss: 0.0556 - val_accuracy: 0.6623 - val_loss: 2.3202
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9967 - loss: 0.0196 - val_accuracy: 0.6753 - val_loss: 2.2699
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9837 - loss: 0.0404 - val_accuracy: 0.6753 - val_loss: 2.3917
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9935 - loss: 0.0207 - val_accuracy: 0.6558 - val_loss: 2.4605
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9886 - loss: 0.0283 - val_accuracy: 0.6818 - val_loss: 2.6044
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9919 - loss: 0.0421 - val_accuracy: 0.6688 - val_loss: 2.4425
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9788 - loss: 0.0592 - val_accuracy: 0.6753 - val_loss: 2.3901
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9951 - loss: 0.0183 - val_accuracy: 0.6753 - val_loss: 2.3684
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9935 - loss: 0.0260 - val_accuracy: 0.6753 - val_loss: 2.5820
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9853 - loss: 0.0338 - val_accuracy: 0.6364 - val_loss: 2.9146
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9951 - loss: 0.0180 - val_accuracy: 0.6558 - val_loss: 2.6229
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9967 - loss: 0.0161 - val_accuracy: 0.6753 - val_loss: 2.5085
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9805 - loss: 0.0471 - val_accuracy: 0.6818 - val_loss: 2.7485
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0079 - val_accuracy: 0.6753 - val_loss: 2.6764
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0074 - val_accuracy: 0.6623 - val_loss: 2.8040
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9870 - loss: 0.0326 - val_accuracy: 0.6818 - val_loss: 2.6671
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9935 - loss: 0.0198 - val_accuracy: 0.6688 - val_loss: 2.7705
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9984 - loss: 0.0093 - val_accuracy: 0.6818 - val_loss: 2.8543

In [72]:
def build_model(hp) :
  model = Sequential()

  counter = 0 ;

  for i in range(hp.Int('num_layers') , min_value = 1 , max_value = 10):
    model.add(Dense(72 , activation= 'relu'))

  model.add(Dense(1 , activation = 'sigmoid'))

  model.compile(optimizer = 'adam' , loss = 'binary_crossentropy' , metrics = ['accuracy'])

  return model

In [86]:
def build_model(hp):
  model = Sequential()
  counter = 0

  for i in range(hp.Int('num_layers', min_value=1, max_value=10)):
    if counter == 0:
      model.add(Dense(
          hp.Int('units_' + str(i), min_value=8, max_value=128, step=8),
          activation=hp.Choice('activation_' + str(i), values=['relu', 'tanh', 'sigmoid']),
          input_dim=8
      ))
      model.add(Dropout(hp.Choice('dropout_' + str(i), values=[0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])))
    else:
      model.add(Dense(
          hp.Int('units_' + str(i), min_value=8, max_value=128, step=8),
          activation=hp.Choice('activation_' + str(i), values=['relu', 'tanh', 'sigmoid'])
      ))
      model.add(Dropout(hp.Choice('dropout_' + str(i), values=[0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])))
    counter += 1

  model.add(Dense(1, activation='sigmoid'))

  model.compile(
      optimizer=hp.Choice('optimizer', values=['rmsprop', 'adam', 'sgd', 'nadam', 'adadelta']),
      loss='binary_crossentropy',
      metrics=['accuracy']
  )

  return model

In [88]:
tuner = kt.RandomSearch(build_model , objective = 'val_accuracy' , max_trials = 3 , directory = 'mydir' , project_name = 'Final1')

In [89]:
tuner.search(X_train , y_train , epochs = 5 , validation_data = (X_test , y_test))

Trial 3 Complete [00h 00m 06s]
val_accuracy: 0.6428571343421936

Best val_accuracy So Far: 0.6428571343421936
Total elapsed time: 00h 00m 16s

In [90]:
tuner.get_best_hyperparameters()[0].values

{'num_layers': 4,
 'units_0': 16,
 'activation_0': 'sigmoid',
 'dropout_0': 0.1,
 'optimizer': 'adam',
 'units_1': 8,
 'activation_1': 'relu',
 'dropout_1': 0.1,
 'units_2': 8,
 'activation_2': 'relu',
 'dropout_2': 0.1,
 'units_3': 8,
 'activation_3': 'relu',
 'dropout_3': 0.1}

In [91]:
model = tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.13/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'adam', because it has 2 variables whereas the saved optimizer has 22 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [92]:
model.fit(X_train, y_train, batch_size=32, epochs=200,initial_epoch=6 ,  validation_data=(X_test, y_test))

Epoch 7/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 2s 17ms/step - accuracy: 0.6531 - loss: 0.6726 - val_accuracy: 0.6429 - val_loss: 0.6646
Epoch 8/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6498 - loss: 0.6647 - val_accuracy: 0.6429 - val_loss: 0.6560
Epoch 9/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6564 - loss: 0.6556 - val_accuracy: 0.6429 - val_loss: 0.6501
Epoch 10/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6547 - loss: 0.6480 - val_accuracy: 0.6429 - val_loss: 0.6445
Epoch 11/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6515 - loss: 0.6531 - val_accuracy: 0.6429 - val_loss: 0.6382
Epoch 12/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.6434 - val_accuracy: 0.6429 - val_loss: 0.6310
Epoch 13/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6515 - loss: 0.6303 - val_accuracy: 0.6429 - val_loss: 0.6229
Epoch 14/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6531 - loss: 0.6230 - val_accuracy: 0.6429 - val_loss: 0.6131
Epoch 15/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6531 - loss: 0.6136 - val_accuracy: 0.6429 - val_loss: 0.6015
Epoch 16/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6564 - loss: 0.5952 - val_accuracy: 0.6429 - val_loss: 0.5880
Epoch 17/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6645 - loss: 0.5862 - val_accuracy: 0.6429 - val_loss: 0.5753
Epoch 18/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6547 - loss: 0.5840 - val_accuracy: 0.6429 - val_loss: 0.5645
Epoch 19/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6661 - loss: 0.5796 - val_accuracy: 0.6558 - val_loss: 0.5548
Epoch 20/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6889 - loss: 0.5607 - val_accuracy: 0.7078 - val_loss: 0.5466
Epoch 21/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6987 - loss: 0.5567 - val_accuracy: 0.7662 - val_loss: 0.5444
Epoch 22/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7085 - loss: 0.5607 - val_accuracy: 0.7468 - val_loss: 0.5387
Epoch 23/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7215 - loss: 0.5271 - val_accuracy: 0.7532 - val_loss: 0.5342
Epoch 24/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6987 - loss: 0.5375 - val_accuracy: 0.7273 - val_loss: 0.5302
Epoch 25/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7313 - loss: 0.5339 - val_accuracy: 0.7143 - val_loss: 0.5265
Epoch 26/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7150 - loss: 0.5388 - val_accuracy: 0.7078 - val_loss: 0.5261
Epoch 27/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7134 - loss: 0.5387 - val_accuracy: 0.7078 - val_loss: 0.5256
Epoch 28/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7166 - loss: 0.5326 - val_accuracy: 0.7208 - val_loss: 0.5242
Epoch 29/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7199 - loss: 0.5297 - val_accuracy: 0.7208 - val_loss: 0.5237
Epoch 30/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7427 - loss: 0.5282 - val_accuracy: 0.7143 - val_loss: 0.5225
Epoch 31/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7215 - loss: 0.5279 - val_accuracy: 0.7273 - val_loss: 0.5231
Epoch 32/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7394 - loss: 0.5078 - val_accuracy: 0.7208 - val_loss: 0.5214
Epoch 33/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7736 - loss: 0.5026 - val_accuracy: 0.7143 - val_loss: 0.5215
Epoch 34/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7345 - loss: 0.5252 - val_accuracy: 0.7143 - val_loss: 0.5205
Epoch 35/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7476 - loss: 0.5140 - val_accuracy: 0.7143 - val_loss: 0.5201
Epoch 36/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7541 - loss: 0.5103 - val_accuracy: 0.7143 - val_loss: 0.5213
Epoch 37/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7410 - loss: 0.5099 - val_accuracy: 0.7208 - val_loss: 0.5224
Epoch 38/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7590 - loss: 0.5027 - val_accuracy: 0.7208 - val_loss: 0.5215
Epoch 39/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7443 - loss: 0.5216 - val_accuracy: 0.7208 - val_loss: 0.5190
Epoch 40/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7476 - loss: 0.5111 - val_accuracy: 0.7208 - val_loss: 0.5171
Epoch 41/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7590 - loss: 0.5080 - val_accuracy: 0.7208 - val_loss: 0.5157
Epoch 42/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7720 - loss: 0.5086 - val_accuracy: 0.7208 - val_loss: 0.5128
Epoch 43/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7752 - loss: 0.4940 - val_accuracy: 0.7338 - val_loss: 0.5126
Epoch 44/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7573 - loss: 0.4908 - val_accuracy: 0.7273 - val_loss: 0.5141
Epoch 45/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7541 - loss: 0.5075 - val_accuracy: 0.7143 - val_loss: 0.5156
Epoch 46/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7443 - loss: 0.4940 - val_accuracy: 0.7208 - val_loss: 0.5140
Epoch 47/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7622 - loss: 0.4907 - val_accuracy: 0.7532 - val_loss: 0.5115
Epoch 48/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7606 - loss: 0.5074 - val_accuracy: 0.7468 - val_loss: 0.5117
Epoch 49/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7736 - loss: 0.5058 - val_accuracy: 0.7468 - val_loss: 0.5098
Epoch 50/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7459 - loss: 0.4936 - val_accuracy: 0.7273 - val_loss: 0.5135
Epoch 51/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7622 - loss: 0.5004 - val_accuracy: 0.7338 - val_loss: 0.5132
Epoch 52/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7590 - loss: 0.4839 - val_accuracy: 0.7468 - val_loss: 0.5117
Epoch 53/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7524 - loss: 0.4980 - val_accuracy: 0.7468 - val_loss: 0.5105
Epoch 54/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7606 - loss: 0.5045 - val_accuracy: 0.7532 - val_loss: 0.5109
Epoch 55/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7573 - loss: 0.4795 - val_accuracy: 0.7468 - val_loss: 0.5106
Epoch 56/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7590 - loss: 0.4914 - val_accuracy: 0.7468 - val_loss: 0.5107
Epoch 57/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7655 - loss: 0.4928 - val_accuracy: 0.7532 - val_loss: 0.5112
Epoch 58/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7769 - loss: 0.4802 - val_accuracy: 0.7468 - val_loss: 0.5134
Epoch 59/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7671 - loss: 0.5053 - val_accuracy: 0.7403 - val_loss: 0.5145
Epoch 60/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7704 - loss: 0.5002 - val_accuracy: 0.7597 - val_loss: 0.5111
Epoch 61/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7671 - loss: 0.4921 - val_accuracy: 0.7468 - val_loss: 0.5115
Epoch 62/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7720 - loss: 0.4741 - val_accuracy: 0.7403 - val_loss: 0.5138
Epoch 63/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7818 - loss: 0.5038 - val_accuracy: 0.7403 - val_loss: 0.5135
Epoch 64/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7671 - loss: 0.4886 - val_accuracy: 0.7532 - val_loss: 0.5126
Epoch 65/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7590 - loss: 0.4991 - val_accuracy: 0.7532 - val_loss: 0.5114
Epoch 66/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7638 - loss: 0.4875 - val_accuracy: 0.7468 - val_loss: 0.5135
Epoch 67/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7638 - loss: 0.4927 - val_accuracy: 0.7468 - val_loss: 0.5132
Epoch 68/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7769 - loss: 0.4854 - val_accuracy: 0.7532 - val_loss: 0.5132
Epoch 69/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4797 - val_accuracy: 0.7532 - val_loss: 0.5122
Epoch 70/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4785 - val_accuracy: 0.7532 - val_loss: 0.5141
Epoch 71/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7704 - loss: 0.4678 - val_accuracy: 0.7468 - val_loss: 0.5163
Epoch 72/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4745 - val_accuracy: 0.7468 - val_loss: 0.5169
Epoch 73/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4716 - val_accuracy: 0.7532 - val_loss: 0.5129
Epoch 74/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7638 - loss: 0.4805 - val_accuracy: 0.7468 - val_loss: 0.5131
Epoch 75/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7655 - loss: 0.4740 - val_accuracy: 0.7532 - val_loss: 0.5125
Epoch 76/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7638 - loss: 0.4763 - val_accuracy: 0.7532 - val_loss: 0.5114
Epoch 77/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7671 - loss: 0.4885 - val_accuracy: 0.7597 - val_loss: 0.5094
Epoch 78/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7622 - loss: 0.4984 - val_accuracy: 0.7468 - val_loss: 0.5105
Epoch 79/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4816 - val_accuracy: 0.7662 - val_loss: 0.5081
Epoch 80/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7410 - loss: 0.4999 - val_accuracy: 0.7597 - val_loss: 0.5096
Epoch 81/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7752 - loss: 0.4792 - val_accuracy: 0.7727 - val_loss: 0.5084
Epoch 82/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7590 - loss: 0.4788 - val_accuracy: 0.7597 - val_loss: 0.5082
Epoch 83/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7573 - loss: 0.4832 - val_accuracy: 0.7597 - val_loss: 0.5089
Epoch 84/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7671 - loss: 0.4790 - val_accuracy: 0.7662 - val_loss: 0.5074
Epoch 85/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7622 - loss: 0.4808 - val_accuracy: 0.7597 - val_loss: 0.5097
Epoch 86/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7752 - loss: 0.4750 - val_accuracy: 0.7338 - val_loss: 0.5115
Epoch 87/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7671 - loss: 0.4687 - val_accuracy: 0.7597 - val_loss: 0.5091
Epoch 88/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7752 - loss: 0.4634 - val_accuracy: 0.7597 - val_loss: 0.5100
Epoch 89/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7622 - loss: 0.4733 - val_accuracy: 0.7597 - val_loss: 0.5111
Epoch 90/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7785 - loss: 0.4558 - val_accuracy: 0.7662 - val_loss: 0.5094
Epoch 91/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7590 - loss: 0.4981 - val_accuracy: 0.7662 - val_loss: 0.5095
Epoch 92/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7785 - loss: 0.4754 - val_accuracy: 0.7532 - val_loss: 0.5073
Epoch 93/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7736 - loss: 0.4886 - val_accuracy: 0.7662 - val_loss: 0.5057
Epoch 94/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7590 - loss: 0.4874 - val_accuracy: 0.7662 - val_loss: 0.5057
Epoch 95/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7573 - loss: 0.4813 - val_accuracy: 0.7532 - val_loss: 0.5077
Epoch 96/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7687 - loss: 0.4823 - val_accuracy: 0.7662 - val_loss: 0.5054
Epoch 97/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7541 - loss: 0.4904 - val_accuracy: 0.7662 - val_loss: 0.5068
Epoch 98/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7573 - loss: 0.4753 - val_accuracy: 0.7662 - val_loss: 0.5067
Epoch 99/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7720 - loss: 0.4727 - val_accuracy: 0.7403 - val_loss: 0.5094
Epoch 100/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7687 - loss: 0.4854 - val_accuracy: 0.7597 - val_loss: 0.5082
Epoch 101/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4659 - val_accuracy: 0.7597 - val_loss: 0.5061
Epoch 102/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4678 - val_accuracy: 0.7662 - val_loss: 0.5067
Epoch 103/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7573 - loss: 0.4675 - val_accuracy: 0.7597 - val_loss: 0.5058
Epoch 104/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7687 - loss: 0.4860 - val_accuracy: 0.7662 - val_loss: 0.5037
Epoch 105/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4776 - val_accuracy: 0.7662 - val_loss: 0.5030
Epoch 106/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7622 - loss: 0.4717 - val_accuracy: 0.7727 - val_loss: 0.5040
Epoch 107/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7704 - loss: 0.4705 - val_accuracy: 0.7792 - val_loss: 0.5032
Epoch 108/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7541 - loss: 0.4795 - val_accuracy: 0.7662 - val_loss: 0.5015
Epoch 109/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7752 - loss: 0.4725 - val_accuracy: 0.7662 - val_loss: 0.5029
Epoch 110/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7736 - loss: 0.4885 - val_accuracy: 0.7662 - val_loss: 0.5034
Epoch 111/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4623 - val_accuracy: 0.7662 - val_loss: 0.5021
Epoch 112/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4668 - val_accuracy: 0.7662 - val_loss: 0.5028
Epoch 113/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7557 - loss: 0.5045 - val_accuracy: 0.7662 - val_loss: 0.5006
Epoch 114/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4643 - val_accuracy: 0.7792 - val_loss: 0.4984
Epoch 115/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7671 - loss: 0.4716 - val_accuracy: 0.7662 - val_loss: 0.4990
Epoch 116/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4713 - val_accuracy: 0.7727 - val_loss: 0.4991
Epoch 117/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7736 - loss: 0.4700 - val_accuracy: 0.7662 - val_loss: 0.4989
Epoch 118/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4643 - val_accuracy: 0.7727 - val_loss: 0.4984
Epoch 119/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7671 - loss: 0.4918 - val_accuracy: 0.7727 - val_loss: 0.4979
Epoch 120/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4682 - val_accuracy: 0.7662 - val_loss: 0.4983
Epoch 121/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4680 - val_accuracy: 0.7727 - val_loss: 0.4987
Epoch 122/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7524 - loss: 0.4776 - val_accuracy: 0.7727 - val_loss: 0.4985
Epoch 123/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7785 - loss: 0.4774 - val_accuracy: 0.7662 - val_loss: 0.4983
Epoch 124/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7769 - loss: 0.4789 - val_accuracy: 0.7662 - val_loss: 0.4972
Epoch 125/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7769 - loss: 0.4681 - val_accuracy: 0.7727 - val_loss: 0.4972
Epoch 126/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7655 - loss: 0.4871 - val_accuracy: 0.7792 - val_loss: 0.4972
Epoch 127/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7638 - loss: 0.4836 - val_accuracy: 0.7792 - val_loss: 0.4956
Epoch 128/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7752 - loss: 0.4782 - val_accuracy: 0.7792 - val_loss: 0.4949
Epoch 129/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7769 - loss: 0.4680 - val_accuracy: 0.7727 - val_loss: 0.4966
Epoch 130/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7671 - loss: 0.4746 - val_accuracy: 0.7792 - val_loss: 0.4963
Epoch 131/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7899 - loss: 0.4663 - val_accuracy: 0.7727 - val_loss: 0.4966
Epoch 132/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7752 - loss: 0.4731 - val_accuracy: 0.7792 - val_loss: 0.4963
Epoch 133/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7997 - loss: 0.4522 - val_accuracy: 0.7662 - val_loss: 0.4989
Epoch 134/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7769 - loss: 0.4725 - val_accuracy: 0.7727 - val_loss: 0.4964
Epoch 135/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7720 - loss: 0.4652 - val_accuracy: 0.7727 - val_loss: 0.4944
Epoch 136/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4679 - val_accuracy: 0.7792 - val_loss: 0.4953
Epoch 137/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7655 - loss: 0.4777 - val_accuracy: 0.7792 - val_loss: 0.4957
Epoch 138/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7606 - loss: 0.4778 - val_accuracy: 0.7727 - val_loss: 0.4944
Epoch 139/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7769 - loss: 0.4740 - val_accuracy: 0.7727 - val_loss: 0.4937
Epoch 140/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7655 - loss: 0.4633 - val_accuracy: 0.7792 - val_loss: 0.4926
Epoch 141/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4824 - val_accuracy: 0.7792 - val_loss: 0.4933
Epoch 142/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7687 - loss: 0.4767 - val_accuracy: 0.7727 - val_loss: 0.4933
Epoch 143/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7769 - loss: 0.4669 - val_accuracy: 0.7662 - val_loss: 0.4933
Epoch 144/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4749 - val_accuracy: 0.7792 - val_loss: 0.4924
Epoch 145/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7785 - loss: 0.4710 - val_accuracy: 0.7792 - val_loss: 0.4916
Epoch 146/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7492 - loss: 0.4822 - val_accuracy: 0.7792 - val_loss: 0.4928
Epoch 147/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7752 - loss: 0.4645 - val_accuracy: 0.7792 - val_loss: 0.4926
Epoch 148/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4748 - val_accuracy: 0.7727 - val_loss: 0.4926
Epoch 149/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7769 - loss: 0.4739 - val_accuracy: 0.7792 - val_loss: 0.4909
Epoch 150/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4648 - val_accuracy: 0.7792 - val_loss: 0.4899
Epoch 151/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4442 - val_accuracy: 0.7792 - val_loss: 0.4912
Epoch 152/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7687 - loss: 0.4750 - val_accuracy: 0.7792 - val_loss: 0.4898
Epoch 153/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7866 - loss: 0.4625 - val_accuracy: 0.7792 - val_loss: 0.4907
Epoch 154/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4608 - val_accuracy: 0.7792 - val_loss: 0.4918
Epoch 155/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4580 - val_accuracy: 0.7727 - val_loss: 0.4939
Epoch 156/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4615 - val_accuracy: 0.7727 - val_loss: 0.4935
Epoch 157/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7720 - loss: 0.4893 - val_accuracy: 0.7792 - val_loss: 0.4916
Epoch 158/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7736 - loss: 0.4647 - val_accuracy: 0.7857 - val_loss: 0.4923
Epoch 159/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7638 - loss: 0.4643 - val_accuracy: 0.7857 - val_loss: 0.4923
Epoch 160/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7785 - loss: 0.4654 - val_accuracy: 0.7792 - val_loss: 0.4927
Epoch 161/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4775 - val_accuracy: 0.7792 - val_loss: 0.4924
Epoch 162/200