<a href="https://colab.research.google.com/github/Akash14-09/Machine_Learning/blob/main/Working_with_time_and_dates_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
import numpy as np
import pandas as pd

In [24]:
date = pd.read_csv('/content/orders.csv')

time = pd.read_csv('/content/messages.csv')

In [25]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [26]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [27]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [28]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

##Working with Dates Data

In [29]:
date['date'] = pd.to_datetime(date['date'])

In [30]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

1.Extracting Year

In [31]:
date['date_year'] = date['date'].dt.year
date.sample(5)

          date  product_id  city_id  orders  date_year
850 2018-12-28         383       25      15       2018
784 2019-11-07        3076       18      11       2019
474 2019-11-01        3967        2      12       2019
928 2019-01-02        5371       22       4       2019
554 2019-12-11         873       25      26       2019

2.Extracting the month from the dataset

In [32]:
date['date_month_no'] = date['date'].dt.month_name()
date.head()

        date  product_id  city_id  orders  date_year date_month_no
0 2019-12-10        5628       25       3       2019      December
1 2018-08-15        3646       14     157       2018        August
2 2018-10-23        1859       25       1       2018       October
3 2019-08-17        7292       25       1       2019        August
4 2019-01-06        4344       25       3       2019       January

3.Extracting days

In [33]:
date['date_day'] = date['date'].dt.day
date.head()

        date  product_id  city_id  orders  date_year date_month_no  date_day
0 2019-12-10        5628       25       3       2019      December        10
1 2018-08-15        3646       14     157       2018        August        15
2 2018-10-23        1859       25       1       2018       October        23
3 2019-08-17        7292       25       1       2019        August        17
4 2019-01-06        4344       25       3       2019       January         6

In [34]:
date['date_dow'] = date['date'].dt.dayofweek
date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_day,date_dow
0,2019-12-10,5628,25,3,2019,December,10,1
1,2018-08-15,3646,14,157,2018,August,15,2
2,2018-10-23,1859,25,1,2018,October,23,1
3,2019-08-17,7292,25,1,2019,August,17,5
4,2019-01-06,4344,25,3,2019,January,6,6

In [36]:
date['date_dow_name'] = date['date'].dt.day_name()

date.drop(columns = ['product_id' , 'city_id' , 'orders']).head()

        date  date_year date_month_no  date_day  date_dow date_dow_name
0 2019-12-10       2019      December        10         1       Tuesday
1 2018-08-15       2018        August        15         2     Wednesday
2 2018-10-23       2018       October        23         1       Tuesday
3 2019-08-17       2019        August        17         5      Saturday
4 2019-01-06       2019       January         6         6        Sunday

In [39]:
date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_day,date_dow,date_dow_name,date_is_weekend
0,2019-12-10,5628,25,3,2019,December,10,1,Tuesday,0
1,2018-08-15,3646,14,157,2018,August,15,2,Wednesday,0
2,2018-10-23,1859,25,1,2018,October,23,1,Tuesday,0
3,2019-08-17,7292,25,1,2019,August,17,5,Saturday,1
4,2019-01-06,4344,25,3,2019,January,6,6,Sunday,1

In [38]:
date['date_is_weekend'] = np.where(date['date_dow_name'].isin(['Sunday' , 'Saturday']) , 1 , 0)

date.drop(columns = ['product_id' , 'city_id' , 'orders']).head()

,date,date_year,date_month_no,date_day,date_dow,date_dow_name,date_is_weekend
0,2019-12-10,2019,December,10,1,Tuesday,0
1,2018-08-15,2018,August,15,2,Wednesday,0
2,2018-10-23,2018,October,23,1,Tuesday,0
3,2019-08-17,2019,August,17,5,Saturday,1
4,2019-01-06,2019,January,6,6,Sunday,1

Extracting week of the year

In [41]:
date['date_week'] = date['date'].dt.isocalendar().week

date.drop(columns = ['product_id' , 'city_id' , 'orders']).head()

,date,date_year,date_month_no,date_day,date_dow,date_dow_name,date_is_weekend,date_week
0,2019-12-10,2019,December,10,1,Tuesday,0,50
1,2018-08-15,2018,August,15,2,Wednesday,0,33
2,2018-10-23,2018,October,23,1,Tuesday,0,43
3,2019-08-17,2019,August,17,5,Saturday,1,33
4,2019-01-06,2019,January,6,6,Sunday,1,1

Extract the quarter

In [42]:
date['quarter'] = date['date'].dt.quarter
date.drop(columns = ['product_id' , 'city_id' ,'orders']).head()

,date,date_year,date_month_no,date_day,date_dow,date_dow_name,date_is_weekend,date_week,quarter
0,2019-12-10,2019,December,10,1,Tuesday,0,50,4
1,2018-08-15,2018,August,15,2,Wednesday,0,33,3
2,2018-10-23,2018,October,23,1,Tuesday,0,43,4
3,2019-08-17,2019,August,17,5,Saturday,1,33,3
4,2019-01-06,2019,January,6,6,Sunday,1,1,1

Extract Semester

In [43]:
date['semester'] = np.where(date['quarter'].isin([1,2] ) , 1 , 2)
date.drop(columns = ['product_id' , 'city_id' , 'orders']).head()

,date,date_year,date_month_no,date_day,date_dow,date_dow_name,date_is_weekend,date_week,quarter,semester
0,2019-12-10,2019,December,10,1,Tuesday,0,50,4,2
1,2018-08-15,2018,August,15,2,Wednesday,0,33,3,2
2,2018-10-23,2018,October,23,1,Tuesday,0,43,4,2
3,2019-08-17,2019,August,17,5,Saturday,1,33,3,2
4,2019-01-06,2019,January,6,6,Sunday,1,1,1,1

Extract the time elapsed betweeen the dates

In [44]:
import datetime
today = datetime.datetime.today()
today

datetime.datetime(2026, 8, 13, 10, 48, 51, 42099)

In [45]:
today - date['date']

0     2438 days 10:48:51.042099
1     2920 days 10:48:51.042099
2     2851 days 10:48:51.042099
3     2553 days 10:48:51.042099
4     2776 days 10:48:51.042099
                 ...
995   2866 days 10:48:51.042099
996   2807 days 10:48:51.042099
997   2655 days 10:48:51.042099
998   2720 days 10:48:51.042099
999   2494 days 10:48:51.042099
Name: date, Length: 1000, dtype: timedelta64[ns]

In [46]:
(today - date['date']).dt.days

0      2438
1      2920
2      2851
3      2553
4      2776
       ...
995    2866
996    2807
997    2655
998    2720
999    2494
Name: date, Length: 1000, dtype: int64

month passed

In [48]:
np.round((today - date['date']).dt.days / 30.44 , 0)

0      80.0
1      96.0
2      94.0
3      84.0
4      91.0
       ...
995    94.0
996    92.0
997    87.0
998    89.0
999    82.0
Name: date, Length: 1000, dtype: float64

In [49]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [50]:
#converting it into a datetime datatype

In [51]:
time['date'] = pd.to_datetime(time['date'])

In [52]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [53]:
time['hour'] = time['date'].dt.hour
time['min'] = time['date'].dt.minute
time['sec'] = time['date'].dt.second

time.head()

,date,msg,hour,min,sec
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

Extract time part

In [54]:
time['time'] = time['date'].dt.time

time.head()

,date,msg,hour,min,sec,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00

time difference

In [55]:
today - time['date']

0     4624 days 09:58:51.042099
1     4488 days 11:08:51.042099
2     4974 days 10:27:51.042099
3     4276 days 10:17:51.042099
4     4673 days 11:37:51.042099
                 ...
995   5263 days 09:58:51.042099
996   4584 days 11:34:51.042099
997   5049 days 11:11:51.042099
998   5165 days 11:14:51.042099
999   4437 days 11:23:51.042099
Name: date, Length: 1000, dtype: timedelta64[ns]

In [56]:
#in seconds
(today - time['date'])/np.timedelta64(1,'s')

0      3.995495e+08
1      3.878033e+08
2      4.297913e+08
3      3.694835e+08
4      4.037891e+08
           ...
995    4.547591e+08
996    3.960993e+08
997    4.362739e+08
998    4.462965e+08
999    3.833978e+08
Name: date, Length: 1000, dtype: float64

In [57]:
#in minutes
(today - time['date'])/np.timedelta64(1,'m')

0      6.659159e+06
1      6.463389e+06
2      7.163188e+06
3      6.158058e+06
4      6.729818e+06
           ...
995    7.579319e+06
996    6.601655e+06
997    7.271232e+06
998    7.438275e+06
999    6.389964e+06
Name: date, Length: 1000, dtype: float64

In [58]:
#in hours
(today - time['date'])/np.timedelta64(1,'h')

0      110985.980845
1      107723.147512
2      119386.464178
3      102634.297512
4      112163.630845
           ...
995    126321.980845
996    110027.580845
997    121187.197512
998    123971.247512
999    106499.397512
Name: date, Length: 1000, dtype: float64